### ISSUE TITLE
Cut release

### ISSUE THREAD

**Issue by MichaelXavier** [ozataman/restful-snap#3]
For the sake of keeping this up with other packages which depend on it, this could use a hackage release. It turns out that neither @ozataman and I do not have access to upload this package to hackage. @mightybyte when you get a chance could you grant us maintainer access on hackage for `restful-snap`? I'm assuming Oz' account is `ozataman`. Mine is `MichaelXavier`. Thanks!

**Comment by mightybyte** [comment]
Done.

**Comment by MichaelXavier** [comment]
Thanks, Doug!
